[package]
name = "private_bot_for_facebook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.23"
serde = "1.0.193"
serde_json = "1.0.109"
